name: First Workflow
on: [workflow_dispatch] # manualy trigger the workflow
jobs:
  first-job:
    runs-on: self-hosted
    permissions:
      security-events: write
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - name: SimpleIOT test
        run: |
              cd /usr/testing
              ./script.sh
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: simpleIOT.sarif
          category: testing
      - name: Print goodbye
        run: echo "Done - bye!"
