name: First Workflow
on: [workflow_dispatch] # manualy trigger the workflow
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Get kernel version
        run: uname -srm
      - name: Print goodbye
        run: echo "Done - bye!"
