name: First Workflow
on: [workflow_dispatch] # manualy trigger the workflow
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Get kernel version
        run: uname -srm
      - name: SimpleIOT test
        run: |
              cd /var/opt/hcl/appscansource/samples/simpleIOT
              pwd
              ls -alh
              /opt/hcl/appscansource/bin/appscansrccli scr SimpleIOT.scan
      - name: Print goodbye
        run: echo "Done - bye!"
