name: First Workflow
on: [workflow_dispatch] # manualy trigger the workflow
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: SimpleIOT test
        run: |
              cd /usr/testing
              ./script.sh
      - name: Print goodbye
        run: echo "Done - bye!"
