name: First Workflow
on: [workflow_dispatch] # manualy trigger the workflow
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Get kernel version
        run: uname -srm
      - name: SimpleIOT test
        run: |
              cd /usr/testing
              docker run -it --rm --env-file env.list --add-host usriappscansv:10.253.160.244 --volume /var/opt/hcl/appscansource/samples/simpleIOT/:/workspace/ appscan/appscan-src-cli:10.4.0 script /workspace/SimpleIOT.scan
      - name: Print goodbye
        run: echo "Done - bye!"
